version: "3.8"

services:
  flask:
    build: ./app
    container_name: flask
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=True
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - VKID=${VKID}
      - VK_SECRET=${VK_SECRET}
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    command: python app.py
  mysql_db:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql